<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >
   <head>
       <title>Fantastic figurines</title>
       <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	   <meta name="author" content="Tonaï" />
	   <meta name="description" content="Site personnel réservé exclusivement à la peinture de figurines fantastiques." />
	   <meta name="keywords" content="figurines, fantastiques, peinture, tonaï, presentation" />
	   <meta name="reply-to" content="tonai59@hotmail.fr" />
	   <link rel="shortcut icon" type="image/x-icon" href="icone/fantasticfigurines.jpg" />
	   <link rel="stylesheet" media="screen" type="text/css" title="Design" href="design.css" />
   </head>
   <body>
       <?php include('menu.html');?>
	    <div id="corps">
			<h1>Présentation</h1>
			<p>Bienvenue, visiteur, sur mon site dédié principalement à ma passion qui est : la peinture sur figurine!</p>
			<p>Tout d'abord, une petite présentation s'impose. Je m'appelle Tony CABAYE, j'ai 21 ans et j'habite à Lille. Je suis étudiant et je fais mes études à l'Ecole Centrale de Lille, une école d'ingénieur généraliste se situant sur le campus de Lille 1 à Villeneuve d'ascq. Je fais aussi parti de l'association des "Canonniers" se trouvant à Lambersart prés de lille. Enfin! Le pseudo, que j'utilise à chaque fois comme sur Créafigs', par exemple, c'est : <strong>Tonaï</strong>.</p>
			<p>Je peins des figurines depuis 1999. J'ai d'ailleurs reçu mes premières figurines à l'occasion de mon 14<sup>ème</sup> anniversaire avec une boîte de démarrage de Warhammer 40000, rien de bien original de ce côté là. J'ai rapidement cherché à améliorer la qualité de mes figurines, même si celles-ci étaient toutes d'abord des figurines destinées au jeu. J'ai appris la peinture par moi-même en lisant principalement "White Dwarf" et en m'inspirant des résultats du "Golden Demon" qui étaient et qui est toujours pour moi une grande source de motivation.<br/>
			J'ai donc commencé à peindre des "Sapces Marines" Games Workshop en essayant de toujours passer plus de temps sur mes escouades. Je suis ensuite passé aux "Eldars", mais je passais dorénavant déjà trop de temps sur chaque figurine qu'il m'était impossible de peindre une armée entière. J'ai ensuite peins des figurines "Inquisitors" qui m'ont rapidement découragé de part leur taille (54mm). Ce n'est qu'avec beaucoup de self motivation que j'ai quand même réussis à en terminer 6. Puis je suis passé aux figurines Rackham, d'abord en temps qu'armée : j'ai commencé une armée de Wolfen dont aucune figurines n'est peinte, puis j'ai choisi des figurines plus petites et qui m'attiraient beaucoup (les Fiannas), d'abord pour les peindre pour le plaisir, puis finalement j'ai réussit à terminer un petit contingent pour me constituer une petite armée de barbare Keltois exclusivement constitué de personnages féminins. A partit de là, j'ai de plus en plus songé à faire de la figurine d'exposition et c'est à ce moment que je suis rentré chez les "Canonniers". C'était en 2005.</p>
			<p>La figurine qui marque un vrai pas dans ma peinture est Viraë. C'est d'ailleurs une figurine "hybride" car c'est une figurine pour le jeu sur laquelle j'ai particulièrement poussé ma peinture et c'est grâce à elle que j'ai gagné mes premières récompense dans les concours. A partir de ce moment j'ai pris conscience du fait que j'avais un certain niveau et que je pouvais me lancer plus sérieusement dans les concours.<br/>
			J'ai continué alors dans le Rackham avec le Rôdeur Wolfen et Maelÿn pour m'en détacher progressivement avec des figurines comme Gollum (Seigneur des anneaux, Games Workshop. Retour aux sources ^^), comme Bakabou (MSB Toys) et la desdemone qui est en cours (Yliad).<br/>
			Notons aussi la commande que j'ai reçu de Matou sur Créafigs' : l'oxydée. Cette étape est aussi importante pour moi, car c'est la preuve qu'on commence à me remarquer. Ca m'a fait extrêmement plaisir, car c'est un peu le passage "dans la cour des grands" qui s'ouvre enfin!</p>
			<p>Concernant mon style de peinture. Il n'est pas encore vraiment définissable car j'expérimente toujours de nouvelles techniques, de nouvelles couleurs ou combinaisons de couleurs, de nouveaux effets...etc. Je n'ai pas encore suffisamment de "bouteille" pour avoir réellement de recette toute prête. Par contre je m'impose un certain ordre quand je peins une figurine. En effet, je ne maitrîse pas encore la fabrication de socle digne de ce nom et c'est quelque choses qui me rebute à faire si la figurine est déjà finie au niveau de la peinture. Une fois la peinture finie, je n'aime pas "perdre" mon temps sur le socle car j'ai très envie de passer à autre chose après avoir passé beaucoup de temps sur la peinture. Maintenant je m'impose la construction du socle <strong>avant</strong> la peinture de la figurine. Ensuite, concernant la peinture, je peins en commençant par les couches les plus près du corps pour finir par les détails les plus éloignés. C'est à dire, par exemple, que je vais commencer par la peinture de la peau, puis celle des habits qui sont <strong>sur</strong> la peau, puis par peindre les objets <strong>sur</strong> les habits, puis éventuellement les détails <strong>sur</strong> ces objets...etc.</p>
			<p>Aujourd'hui grace au stage du sculpture organisé par la BDOW avec Cyril Roquelaine, je me lance aussi dans la sculpture, c'est encore tout récent pour moi, et le travail ne demande qu'à s'affiner. La sculpture ouvre alors de nouveau horizons pour des pièces inédites qui j'espère verront le jour. Ca commence alors avec Gally, mais chut!... vous le découvrirez bientôt.</p>
	    </div>
   </body>
</html>